### ISSUE TITLE
-1008 error

### ISSUE THREAD

**Issue by xiaoyuanzh** [ZJU-FAST-Lab/LBFGS-Lite#1] opened 2020-12-22 02:59 UTC
a rounding error occurred.  no line search step satisfy the sufficient decrease and curvature condition.  How to fix it?

**Comment by ZhepeiWang** [comment] 2020-12-22 03:09
Rounding error usually occurs in two situations. The first one is that the **gradient norm is already small enough** considering the problem scale. The second one is that the provided **gradient is not consistent with the function** (usually incorrect gradient or failing in C2 assumption). To be honest, I almost always obtain such an error every time when I make mistakes on the gradient. I wonder if you can check the consistency, or provide the concrete form for objective function and its gradient to see if it is caused by possible underlying bugs.

**Comment by xiaoyuanzh** [comment] 2020-12-22 03:12
it is very useful.  I will check my gradient. 
I wonder the performance of numerical gradient?

**Comment by ZhepeiWang** [comment] 2020-12-22 03:18
I'm afraid that I have no idea about the performance under numerical gradient (if finite difference is used). Numerical gradient, especially FD, can suffer from bad numerical condition. To partially handle such situations, the line search in this solver will automatically change to the trivial one instead of the More-Thunete one, of which the former is more robust in FD cases. However, these modifications are still tricks. I recommend you to use Complex Step or Automatic Differentiation to achieve better precision if possible.

**Comment by ZhepeiWang** [comment] 2020-12-22 11:06
Close this issue. You may reopen it if further information.

**Closed as completed by ZhepeiWang** 2020-12-22 11:06 UTC

**Comment by xiaoyuanzh** [comment] 2020-12-22 16:08
hi,
   I have one more question. If we use, b spline optimization and uniform B spline.
How we make sure that, the starting point and end point lies on the starting position and ending position of the robot?

**Comment by ZhepeiWang** [comment] 2020-12-25 09:27
Sorry, personally, I do not prefer B spline in trajectory optimization for robot planning. As for this question, I cannot provide you some useful information. Maybe you can ask @bigsuperZZZX
